In [2]:
import numpy

In [1]:
import torch

In [5]:
q=torch.tensor([[1,2,3,4],[5,6,7,8]])
q=q.view(2,2,2)
print(q)
p=q.transpose(1,2)
p

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


tensor([[[1, 3],
         [2, 4]],

        [[5, 7],
         [6, 8]]])

In [9]:
k=torch.tensor([[1,1,1,1],[2,2,2,2]])
print(k.size(0))
k.size(1)

2


4

In [13]:
a=torch.tensor([[1,2],[2,3],[3,4]])
a

tensor([[1, 2],
        [2, 3],
        [3, 4]])

In [15]:
print(a.transpose(0,1))
print(a)
a.transpose(-2,-1)

tensor([[1, 2, 3],
        [2, 3, 4]])
tensor([[1, 2],
        [2, 3],
        [3, 4]])


tensor([[1, 2, 3],
        [2, 3, 4]])

In [16]:
import math

In [25]:
a=torch.tensor([[[1],[1]],[[2],[2]]])
b=torch.tensor([[[0],[0]],[[1],[2]]])
print(a.size())
print((a@b.transpose(-1,-2)).size())
a@b.transpose(-2,-1)

torch.Size([2, 2, 1])
torch.Size([2, 2, 2])


tensor([[[0, 0],
         [0, 0]],

        [[2, 4],
         [2, 4]]])

In [29]:
a=torch.tensor([[[1],[1]],[[2],[2]]])
print(a.size())
print(a.transpose(-1,-2))
a.transpose(-1,-2).size()

torch.Size([2, 2, 1])
tensor([[[1, 1]],

        [[2, 2]]])


torch.Size([2, 1, 2])

In [31]:
torch.ones(2,2).size()

torch.Size([2, 2])

In [43]:
torch.tril(torch.ones(4,4)).view(1,1,4,4)
bias=torch.tril(torch.ones(4,4)).view(1,1,4,4)
bias

tensor([[[[1., 0., 0., 0.],
          [1., 1., 0., 0.],
          [1., 1., 1., 0.],
          [1., 1., 1., 1.]]]])

In [46]:
att=torch.tensor([[2.0,2.0,2.0,2.0],[2.0,2.0,2.0,2.0],[2.0,2.0,2.0,2.0],[2.0,2.0,2.0,2.0]])
att.size()
att.view(1,1,4,4)

tensor([[[[2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.]]]])

In [54]:
att=att.masked_fill(bias[:,:,:4,:4] == 0, float("-inf"))

In [57]:
from torch.nn import functional as F
att=F.softmax(att,-1)

In [ ]:
att

tensor([[[[1.0000, 0.0000, 0.0000, 0.0000],
          [0.5000, 0.5000, 0.0000, 0.0000],
          [0.3333, 0.3333, 0.3333, 0.0000],
          [0.2500, 0.2500, 0.2500, 0.2500]]]])

In [2]:
sum(i for i in range(5))

10

In [4]:
import torch
torch.arange(0,5)

tensor([0, 1, 2, 3, 4])

In [6]:
a=torch.tensor([[[1],[1]],[[2],[2]]])
(a.view(2*2,a.size(-1))).size()

torch.Size([4, 1])

In [10]:
logits=torch.tensor([1.0,2.0,3.0,4.0,5.0,6.0,7.0])
v, _ = torch.topk(logits, min(3, logits.size(-1)))
logits[logits < v[[-1]]] = -float('Inf')


In [11]:
logits

tensor([-inf, -inf, -inf, -inf, 5., 6., 7.])

In [9]:
import torch
print(torch.ones(5).shape)
print(torch.ones(5).size())

torch.Size([5])
torch.Size([5])


In [5]:
torch.zero_().size()

TypeError: zero_() missing 1 required positional arguments: "input"

In [24]:
a=torch.tensor([[1,1,1,1],[1,1,1,1]])
a.split(2,1)
a.size()

torch.Size([2, 4])

In [18]:
101/10

10.1

In [27]:
a.transpose(-1,-2).size()

torch.Size([4, 2])

In [26]:
a.size()

torch.Size([2, 4])

In [28]:
torch.tril(torch.ones(5,5))

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [29]:
a.masked_fill?

Docstring:
masked_fill(mask, value) -> Tensor

Out-of-place version of :meth:`torch.Tensor.masked_fill_`
Type:      builtin_function_or_method

In [33]:
a=torch.tensor([[1.0,1.0],[2.0,2.0]])

In [36]:
from torch.nn import functional as F
F.softmax(a,dim=1)

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])