In [3]:
import torch
a=torch.tensor([[1,1,1,1,1,1],[2,2,3,3,4,4]])
a.split(2,-1)

(tensor([[1, 1],
         [2, 2]]),
 tensor([[1, 1],
         [3, 3]]),
 tensor([[1, 1],
         [4, 4]]))

In [ ]:
cls_token=torch.ones(2,2)
a=torch.tensor([[[1,1,1,1],[1,1,1,1]],[[2,2,3,3],[2,2,3,3]]])
a.size()

torch.Size([2, 2, 4])

In [9]:
# cls_token.view(1,1,4)

In [10]:
b=torch.cat((a,cls_token),dim=1)
b.size()

RuntimeError: Tensors must have same number of dimensions: got 3 and 1

In [13]:
torch.ones(2,2,2).size()

torch.Size([2, 2, 2])

In [23]:
from  torch.nn  import functional as F
a=torch.ones(4,5)
a=F.softmax(a,dim=-1)
print(a.size())
target=torch.ones(4).long()
F.cross_entropy(a,target)

torch.Size([4, 5])


tensor(1.6094)

In [14]:
input = torch.randn(3, 5, requires_grad=True)
target = torch.randint(5, (3,), dtype=torch.int64)

In [18]:
print(input.size())
input

torch.Size([3, 5])


tensor([[ 1.7972, -0.4568,  0.1899, -0.1783, -0.8763],
        [-0.2489,  2.6401,  0.5897,  0.0211, -1.6916],
        [ 1.2577,  0.5953,  1.1562,  1.8564,  0.3332]], requires_grad=True)

In [19]:
print(target.size())
target

torch.Size([3])


tensor([1, 0, 4])

In [26]:
a=torch.tensor([[0.2000, 0.1000, 0.4000, 0.3000, 0.6000],
        [0.2000, 0.2000, 0.2000, 0.1000, 0.4000],
        [0.4000, 0.3000, 0.6000, 0.2000, 0.2000],
        [0.2000,0.4000, 0.3000, 0.6000, 0.2000]])
a.argmax(dim=-1)

tensor([4, 4, 2, 3])